[phases.setup]
nixPkgs = [
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "dbus",
  "libxkbcommon",
  "xorg.libX11",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "expat",
  "xorg.libxcb",
  "pango",
  "cairo",
  "alsa-lib",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXtst",
  "gtk3",
  "glib"
]

[phases.install]
cmds = ["npm install", "npx remotion browser ensure"]